title: "Enix Yu's Blog"
subtitle: "Geek is an attitude"
github: "//github.com/enix223"
avater: "author.jpg"
baseurl: ""

cv:
  # Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
  #style: styles-2
  #style: styles-3
  #style: styles-4
  #style: styles-5
  #style: styles-6


  #Profile information
  title: 'Resume - Enix Yu'
  name: Enix Yu
  tagline: Full Stack Developer
  pic: avatar.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

  #sidebar links
  email: enix223@gmail.com
  phone: +86 13826022357
  website: www.enixyu.com #do not add http://
  linkedin: enixyu
  github: enix223
  twitter: '@enixyu'
  stackoverflow: '2717397' # The id of the stackoverflow user account

comments :
  provider : duoshuo
  duoshuo :
    short_name : enixyu
  disqus :
      short_name : enixyu

permalink: pretty
markdown: kramdown #rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://enix223.github.io/'
  relativeLinks: 'http://enix223.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "categories"
        field:
          element: "text"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Python"
              value: "python"
            - name: "Embedded-System"
              value: "embedded-system"
            - name: "Objective-C"
              value: "objectivec"
            - name: "NLP"
              value: "nlp"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
